 Provenance

on:
  push:
    branches: [main]
  release:
    types: [created]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  actions: read
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      digests: ${{ steps.hash.outputs.digests }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build your artifacts
        run: |
          echo "Building artifacts..."
          # Replace these example artifacts with your actual build commands
          echo "artifact1" > artifact1.txt
          echo "artifact2" > artifact2.txt

      - name: Generate SHA256 hashes for artifacts
        id: hash
        run: |
          set -euo pipefail
          files=$(ls artifact*.txt)
          echo "digests=$(sha256sum $files | base64 -w0)" >> "${GITHUB_OUTPUT}"

  provenance:
    needs: build
    permissions:
      actions: read
      id-token: write
      contents: write
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v1.4.0
    with:
      base64-subjects: ${{ needs.build.outputs.digests }}
      upload-assets: true  # Upload provenance file as release asset

